### ISSUE TITLE
Failed to load plug-in script: Error: Invalid entity type.

### ISSUE THREAD

**Issue by kendfrey** [Basssiiie/OpenRCT2-ParkRatingInspector#13]
**Describe the bug**
Upon loading a park, OpenRCT2 outputs this error message:
> Failed to load plug-in script: Error: Invalid entity type.

**To reproduce**
1. Install the latest OpenRCT2 (0.3.4.1)
1. Install ParkRatingInspector
1. Run openrct2.com
1. Start a new scenario
1. ParkRatingInspector is not loaded
1. See the output from openrct2.com

**Expected behavior**
The plugin should load and work.

**Notes**
I suspect this is due to changes to the "peep", "guest", and "staff" entity types.

**Comment by Basssiiie** [comment]
@kendfrey You're correct that the readme does not mention it unfortunately. It is mentioned in big letters on the [download page](https://github.com/Basssiiie/OpenRCT2-ParkRatingInspector/releases/tag/v0.1), I'm afraid I can't make them any bigger. 😁
